shop_project/shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('products/<int:product_id>', views.product, name='product'),

  path('customers/', views.customers, name='customers'),
  path('customers/<int:customer_id>', views.customer, name='customer'),

  path('products/<int:product_id>/comment_form', views.comment_form, name='comment_form'),

  path('products/<int:product_id>/question_form', views.question_form, name='question_form'),

  path('questions/<int:question_id>/response_form', views.response_form, name='response_form'),

  path('comments/<int:comment_id>/commentresponse_form', views.commentresponse_form, name='commentresponse_form'),
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app import views
from contact_app import views
from profile_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_app/', include('shop_app.urls')),
    path('contact_app/', include('contact_app.urls')),
    path('profile_app/', include('profile_app.urls')),
]

shop_project/shop_app/models.py
from django.db import models

class Product(models.Model):
  name = models.CharField(max_length=264)
  price = models.DecimalField(max_digits=5, decimal_places=2)
  description = models.TextField()
  image = models.ImageField(default='static/images/image.png', upload_to='static/images/')

  def __str__(self):
    return self.name

  def __repr__(self):
    return "<Product {}>".format(self.name)


class Customer(models.Model):
  first_name = models.CharField(max_length=264)
  last_name = models.CharField(max_length=264)
  email = models.EmailField(max_length=264)
  password = models.CharField(max_length=264)
  profile_picture = models.ImageField(default='static/images/profile.jpg', upload_to='static/images/profile_pictures/')

  def __str__(self):
    return self.email

  def __repr__(self):
    return "<Customer {}>".format(self.email)



class Comment(models.Model):
  username = models.CharField(max_length=264)
  text = models.TextField()
  date = models.DateField()
  product = models.ForeignKey(Product, on_delete=models.CASCADE)

  def __str__(self):
    return self.username

  def __repr__(self):
    return "<Comment {}>".format(self.username)


class Question(models.Model):
  username = models.CharField(max_length=264)
  title = models.CharField(max_length=264)
  text = models.TextField()
  product = models.ForeignKey(Product, on_delete=models.CASCADE)

  def __str__(self):
    return self.username

  def __repr__(self):
    return "<Question {}>".format(self.username)


class Response(models.Model):
  username = models.CharField(max_length=264)
  text = models.TextField()
  question = models.ForeignKey(Question, on_delete=models.CASCADE)

  def __str__(self):
    return self.username

  def __repr__(self):
    return "<Question {}>".format(self.username)




class CommentResponse(models.Model):
  username = models.CharField(max_length=264)
  text = models.TextField()
  comment = models.ForeignKey(Comment, on_delete=models.CASCADE)


  def __str__(self):
    return self.username

  def __repr__(self):
    return "<CommentResponse {}>".format(self.username)





    

shop_project/shop_app/forms.py
from django import forms
from shop_app.models import Comment, Question, Response , CommentResponse


class CommentForm(forms.ModelForm):
  class Meta:
    model   = Comment
    fields  = ['username', 'text']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'comment-username',
        'placeholder': 'username',
        'required': True
      }),
      'text': forms.Textarea(attrs={
        'id': 'comment-text',
        'placeholder': 'Write a comment here...',
        'required': True
      })
    }


class QuestionForm(forms.ModelForm):
  class Meta:
    model   = Question
    fields  = ['username', 'title', 'text']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'question-username',
        'placeholder': 'username',
        'required': True
      }),
      'title': forms.TextInput(attrs={
        'id': 'question-title',
        'placeholder': 'title',
        'required': True
      }),
      'text': forms.Textarea(attrs={
        'id': 'question-text',
        'placeholder': 'Write a question here...',
        'required': True
      })
    }


class ResponseForm(forms.ModelForm):
  class Meta:
    model   = Response
    fields  = ['username', 'text']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'response-username',
        'placeholder': 'username',
        'required': True
      }),
      'text': forms.Textarea(attrs={
        'id': 'response-text',
        'placeholder': 'Write a response here...',
        'required': True
      })
    }





class CommentResponseForm(forms.ModelForm):
  class Meta:
    model   = CommentResponse
    fields  = ['username', 'text']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'response-username',
        'placeholder': 'comment response',
        'required': True
      }),
      'text': forms.Textarea(attrs={
        'id': 'response-text',
        'placeholder': 'Write a response here...',
        'required': True
      })
    }

shop_project/shop_app/views.py
from django.shortcuts import render, redirect
from shop_app.models import Product, Customer, Comment, Question, Response, CommentResponse
from shop_app.forms import CommentForm, QuestionForm, ResponseForm,CommentResponseForm
import datetime



def index(request):
  user = None
  if request.user.is_authenticated:
    user = request.user
    
  products = Product.objects.all()[:20]
  return render(request, 'index.html', context={ 'products': products, 'user': user })





def product(request, product_id):
  product = Product.objects.get(id=product_id)
  comments = Comment.objects.all().filter(product_id=product_id)
  questions = Question.objects.all().filter(product_id=product_id)

  questions_with_responses = []
  for question in questions:
    question_with_responses = {
      'question': question,
      'responses': Response.objects.all().filter(question_id=question.id)
    }

    questions_with_responses.append(question_with_responses)

  
  comments_with_commentresponses = []
  for comment in comments:
    comment_with_commentresponses = {
      'comment': comment,
      'commentresponses': CommentResponse.objects.all().filter(comment_id=comment.id)
    }

    comments_with_commentresponses.append(comment_with_commentresponses)


  return render(request, 'product.html', context={
      'product': product,
      'comments': comments_with_commentresponses,
      'questions': questions_with_responses,
    })


def customers(request):
  customers = Customer.objects.all()[:20]
  return render(request, 'customers.html', context={ 'customers': customers })


def customer(request, customer_id):
  customer = Customer.objects.get(id=customer_id)
  return render(request, 'customer.html', context={ 'customer': customer })



def comment_form(request, product_id):
  if request.method == 'POST':
    username = request.POST.get('username')
    text = request.POST.get('text')
    product = Product.objects.get(id=product_id)
    date = datetime.datetime.now()
    Comment.objects.get_or_create(username=username, text=text, date=date, product=product)

  return render(request, 'comment_form.html', context={ 'comment_form': CommentForm() })


def question_form(request, product_id):
  if request.method == 'POST':
    username = request.POST.get('username')
    text = request.POST.get('text')
    title = request.POST.get('title')
    product = Product.objects.get(id=product_id)
    Question.objects.get_or_create(username=username, text=text, title=title, product=product)
    return redirect( '/shop_app/products/{}'.format(product_id) )

  return render(request, 'question_form.html', context={ 'question_form': QuestionForm() })


def response_form(request, question_id):
  if request.method == 'POST':
    username = request.POST.get('username')
    text = request.POST.get('text')
    question = Question.objects.get(id=question_id)
    Response.objects.get_or_create(username=username, text=text, question=question)
    return redirect( '/shop_app/products/{}'.format(question.product.id) )

  return render(request, 'response_form.html', context={ 'response_form': ResponseForm() })


def commentresponse_form(request, comment_id):
  if request.method == 'POST':
    username = request.POST.get('username')
    text = request.POST.get('text')
    comment = Comment.objects.get(id=comment_id)
    CommentResponse.objects.get_or_create(username=username, text=text, comment=comment)
    return redirect( '/shop_app/products/{}'.format(comment.product.id) )

  return render(request, 'comment_response_form.html', context={ 'commentresponse_form': CommentResponseForm() })


def commentresponse_form(request, comment_id):
  if request.method == 'POST':
    username = request.POST.get('username')
    text = request.POST.get('text')
    comment = Comment.objects.get(id=comment_id)
    CommentResponse.objects.get_or_create(username=username, text=text, comment=comment)
    return redirect( '/shop_app/products/{}'.format(comment.product.id) )

  
  

shop_project/shop_app/templates/comment_form.html
<!DOCTYPE html>
<html>
<head>
  <title>Add a new Comment</title>
</head>
<body>

  <h1>Ajoutez un commentaire</h1>
  <form action="comment_form" method="POST">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="send comment">
  </form>

</body>
</html>

shop_project/shop_app/templates/comment_response_form.html
<!DOCTYPE html>
<html>
<head>
  <title>Add a new Response</title>
</head>
<body>

  <h1>Ajoutez une reponse au commentaire</h1>
  <form action="" method="POST">
    {{ commentresponse_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="send response">
  </form>

</body>
</html>

shop_project/shop_app/templates/customer.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{{ customer.first_name }} {{ customer.last_name }}</title>
</head>
<body>

  <h1>{{ customer.first_name }} {{ customer.last_name }}</h1>
  <p>{{ customer.email }}</p>
  <img src="http://{{ request.get_host }}/{{ customer.profile_picture }}">

</body>
</html>

shop_project/shop_app/templates/customers.html
<!DOCTYPE html>
<html>
<head>
  <title>Customers</title>
</head>
<body>

  {% for customer in customers %}
    <h3>{{ customer.first_name }} {{ customer.last_name }}</h3>
    <a href="{% url 'shop_app:customer' customer.id %}">{{ customer.email }}</a>
  {% endfor %}

</body>
</html>

shop_project/shop_app/templates/index.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title>Home Page</title>
</head>
<body>

  {% include 'partials/navbar.html' %}
  

  <h1>Product List</h1>
  <hr>
  {% for product in products %}
    <h3>{{ product.name }} - ${{ product.price }}</h3>
    <p>{{ product.description }}</p>
    <a href="{% url 'shop_app:product' product.id %}">click here</a>
    <hr>
  {% endfor %}


  </div>

</body>
</html>

shop_project/shop_app/templates/product.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
  <title>{{ product.name }}</title>
</head>
<body>
  <h1>Product Details</h1>
  <img src="http://{{ request.get_host }}/{{ product.image }}">
  <h3>Name: {{ product.name }}</h3>
  <h3>Price: ${{ product.price }}</h3>
  <h3>Description: {{ product.description }}</h3>
  <h1>Comments</h1>
  {% for comment in comments %}
    <h3>{{ comment.comment.username }}</h3>
    <p>{{ comment.comment.text }}</p>
    <hr>
      <h2>Comment Responses:</h2>
    <ul>
    {% for commentresponse in comment.commentresponses %}
      <li>{{ commentresponse.username }}: {{ commentresponse.text }}</li>
    {% endfor %}
    <!-- # name c pr lurl apres lenom de lapp -->
    <a href="{% url 'shop_app:commentresponse_form' comment.comment.id %}">Write a comment response...</a>
    </ul>
  {% endfor %}
  <h1>Questions</h1>
  {% for question in questions %}
    <h1>=========================</h1>
    <div style="background: lightgray;">
      <h3>{{ question.question.username }}</h3>
      <h3>{{ question.question.title }}</h3>
      <p>{{ question.question.text }}</p>
      <br>
    </div>
    <h2>Responses:</h2>
    <ul>
    {% for response in question.responses %}
      <li>{{ response.username }}: {{ response.text }}</li>
    {% endfor %}
    <a href="{% url 'shop_app:response_form' question.question.id %}">Write a response...</a>
    </ul>
  {% endfor %}
</body>

shop_project/shop_app/templates/question_form.html
<!DOCTYPE html>
<html>
<head>
  <title>Add a new Question</title>
</head>
<body>

  <h1>Ajoutez une question</h1>
  <form action="" method="POST">
    {{ question_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="send question">
  </form>

</body>
</html>

shop_project/shop_app/templates/response_form.html
<!DOCTYPE html>
<html>
<head>
  <title>Add a new Response</title>
</head>
<body>

  <h1>Ajoutez une reponse</h1>
  <form action="" method="POST">
    {{ response_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="send response">
  </form>

</body>
</html>