shop_project/profile_app/urls.py
from django.urls import path
from . import views


app_name = 'profile_app'

urlpatterns = [
# le name ici va dans la pages html pour remplacer pour le formulaire
path('signup/', views.signup, name='signup'),
path('login/', views.login_auth, name='login'),
path('logout_auth/', views.logout_auth, name='logout_auth'),
path('profile/<int:user_id>/', views.profile, name='profile'),
path('profile/<int:user_id>/edit/', views.edit_profile, name='edit_profile'),
]

shop_project/shop_app/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('products/<int:product_id>', views.product, name='product'),

  path('customers/', views.customers, name='customers'),
  path('customers/<int:customer_id>', views.customer, name='customer'),

  path('products/<int:product_id>/comment_form', views.comment_form, name='comment_form'),

  path('products/<int:product_id>/question_form', views.question_form, name='question_form'),

  path('questions/<int:question_id>/response_form', views.response_form, name='response_form'),

  path('comments/<int:comment_id>/commentresponse_form', views.commentresponse_form, name='commentresponse_form'),
]

shop_project/shop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from shop_app import views
from contact_app import views
from profile_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop_app/', include('shop_app.urls')),
    path('contact_app/', include('contact_app.urls')),
    path('profile_app/', include('profile_app.urls')),
]

shop_project/profile_app/models.py
from django.db import models

# Create your models here.

shop_project/profile_app/forms.py
from django import forms
from django.contrib.auth.models import User




class SignupForm(forms.ModelForm):
  class Meta:
    model   = User
    fields  = ['username', 'password','first_name', 'last_name']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'username',
        'placeholder': 'username',
        'required': True
      }),
      'password': forms.PasswordInput(attrs={
        'id': 'password',
        'placeholder': 'Write your password',
        'required': True
      }),
      'first_name': forms.TextInput(attrs={
        'id': 'first_name',
        'placeholder': 'Write your first name',
        'required': True
      }),
      'last_name': forms.TextInput(attrs={
        'id': 'last_name',
        'placeholder': 'Write your last name',
        'required': True
      })    
    }


class LoginForm(forms.ModelForm):
  class Meta:
    model   = User
    fields  = ['username', 'password']
    widgets = {
      'username': forms.TextInput(attrs={
        'id': 'login-username',
        'placeholder': 'username',
        'required': True
      }),
      'password': forms.PasswordInput(attrs={
        'id': 'password',
        'placeholder': 'Write your password',
        'required': True
      })  
    }


class ProfileForm(forms.ModelForm):
  class Meta:
    model   = User
    fields  = ['first_name', 'last_name']
    widgets = {
      'first_name': forms.TextInput(attrs={
        'id': 'profile-first_name',
        'placeholder': 'change your first name',
        'required': True
      }),
      'last_name': forms.TextInput(attrs={
        'id': 'profile-last_name',
        'placeholder': 'change your last name',
        'required': True
      })    
    }
 







 


 

shop_project/profile_app/views.py
from django.shortcuts import render, redirect
from profile_app.forms import SignupForm, LoginForm , ProfileForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login , logout

# authenticate permet a idetifier le user et on doit aussi limporter en haut

def signup(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		User.objects.create_user(username=username, password=password, first_name=first_name, last_name=last_name)
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
	return render(request, 'signup.html', context={ 'signup_form': SignupForm() })




def login_auth(request):
	if request.method == 'POST':
		username  = request.POST.get('username')
		password  = request.POST.get('password')
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect('/shop_app/')
	return render(request, 'login.html', context={ 'login_form': LoginForm() })


def logout_auth(request):
	logout(request)
	return redirect('/shop_app/')




def profile(request, user_id):
	user = User.objects.get(id=user_id)
	
	return render(request, 'profile.html', context={ 'user': user })


def edit_profile(request, user_id):
	user = User.objects.get(id=user_id)
	redirect_link = '/profile_app/profile/{}'.format(user_id)
	if user_id != request.user.id:
		return redirect(redirect_link)

	if request.method == 'POST':
		user.first_name = request.POST.get('first_name')
		user.last_name = request.POST.get('last_name')
		user.save()
		return redirect(redirect_link)

	
	profile_form = ProfileForm(initial={
			'first_name' : user.first_name,
			'last_name': user.last_name
	})
	return render(request, 'profile_edit.html', context={ 'profile_form': profile_form })

shop_project/profile_app/templates/login.html
<!DOCTYPE html>
<html>
<head>
  <title>login</title>
</head>
<body>

  <h1>login</h1>
  <form action="" method="POST">
    {{ login_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="login">
  </form>
  
</body>
</html>

shop_project/profile_app/templates/profile.html
<!DOCTYPE html>
<html>
<head>
  <title>Profile</title>
</head>
<body>
<div class="container">
	<div class="row">
		<div class="card" style="width: 18rem;">
  			<div class="card-body">
  			<h3>User :</h3>
    		<h3 class="card-title">{{ user.username }}</h3>
    		<p class="card-text">
  			<label>first name:</label>
    		{{ user.first_name }}
   			<br>
   			<label>last name:</label>
  			{{ user.last_name }}</p>
  			{% if request.user.id == user.id %}
  			  <a href="{% url 'profile_app:edit_profile' user.id %}" class="btn btn-primary">Edit Profile</a>
  			{% endif %}
  			</div>
  		</div>
	</div>
</div>
</body>
</html>

shop_project/profile_app/templates/profile_edit.html
<!DOCTYPE html>
<html>
<head>
  <title>login</title>
</head>
<body>

  <h1>login</h1>
  <form action="" method="POST">
    {{ profile_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="login">
  </form>

</body>
</html>

shop_project/profile_app/templates/signup.html
<!DOCTYPE html>
<html>
<head>
  <title>signup</title>
</head>
<body>

  <h1>signup</h1>
  <hr>
  <form action="" method="POST">
    {{ signup_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="submit" value="signup">
  </form>

</body>
</html>